------------------------------------- FINESS -------------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_finess as
select FINESS, NUM_FINESS_ET, NUM_FINESS_EJ, RAISON_SOCIALE, RAISON_SOCIALE_LONGUE, COMPLEMENT_RAISON_SOCIALE,
COMPLEMENT_DISTRIBUTION,NUM_VOIE,TYPE_VOIE, LIBELLE_VOIE, LIEU_DIT_BP, CODE_COMMUNE, DEPARTEMENT, LIBELLE_DEPARTEMENT, 
LIGNE_ACHEMINEMENT, TELEPHONE, TELECOPIE, CATEGORIE_ETABLISSEMENT, LIBELLE_CATEGORIE_ETABLISSEMENT, 
CATEGORIE_AGREGAT_ETABLISSEMENT, LIBELLE_AGREGAT_ETABLISSEMENT, SIRET, CODE_APE, CODE_MFT, LIBELLE_MFT, CODE_SPH, LIBELLE_SPH, 
DATE_OUVERTURE FROM "REF_MARKETPLACE"."FINESS"."ETABLISSEMENTS";

----------------------------------------- POSTAL ----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_postal as
select * FROM "REF_MARKETPLACE"."POSTAL"."CODE_POSTAUX";

------------------------------------------- PAYS -----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_pays as
select *  FROM "REF_MARKETPLACE"."MONDE"."PAYS";

------------------------------------------ SITES 5G ----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_reseau5g as
select CODE_OPERATEUR, NOM_OPERATEUR, CODE_SITE_OPERATEUR, ID_STATION_ANFR, X_LAMBERT_93, Y_LAMBERT_93,
DATE_OUVERTURECOMMERCIALE_5G, SITE_5G_2100_M_HZ, SITE_5G_3_5_G_HZ,  CODE_COMMUNE_INSEE, NOM_COMMUNE_INSEE, 
CODE_DEPARTEMENT_INSEE, NOM_DEPARTEMENT_INSEE, CODE_REGION_INSEE, NOM_REGION_INSEE
FROM "REF_MARKETPLACE"."RESEAU"."SITES_5G";

---------------------------------------- ACCIDENTS / CARACTERISTIQUES -----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_acccara as
select * 
FROM "REF_MARKETPLACE"."ACCIDENTS_ROUTIER"."CARACTERISTIQUES";

----------------------------------------- ACCIDENTS / USAGERS ----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_accusagers as
select NUM_ACC, ID_VEHICULE, NUM_VEH, PLACE, CATU, GRAV, SEXE, AN_NAIS, TRAJET 
FROM "REF_MARKETPLACE"."ACCIDENTS_ROUTIER"."USAGERS";

----------------------------------------- ACCIDENTS / VEHICULES -------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_accveh as
select NUM_ACC, ID_VEHICULE, NUM_VEH, SENC, CATV, OBS, OBSM, CHOC, MANV, MOTOR 
FROM "REF_MARKETPLACE"."ACCIDENTS_ROUTIER"."VEHICULES";

-------------------------------------------- BAN / LIEUX DITS -------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_banlieux as
select ID, NOM_LIEU_DIT, CODE_POSTAL, CODE_INSEE, NOM_COMMUNE, X, Y, LON, LAT 
FROM "REF_MARKETPLACE"."BAN"."LIEUX_DITS";

-------------------------------------------- BAN / ADRESSES ------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_banaddr as
select ID, ID_FANTOIR, NUMERO, REP, NOM_VOIE, CODE_POSTAL, CODE_INSEE, NOM_COMMUNE, X, Y, LAT, LON, LIBELLE_ACHEMINEMENT, NOM_AFNOR 
FROM "REF_MARKETPLACE"."BAN"."ADRESSES";

------------------------------------- DPE AMELIORATION -----------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpeamel as
select ID, TD001_DPE_ID, MESURE_AMELIORATION, TR008_EFFORT_INVESTISSEMENT_ID, TR009_ECONOMIE_ID, TR010_RAPIDITE_ROI_ID, 
POURCENTAGE_CREDIT_IMPOT 
FROM "REF_MARKETPLACE"."DPE"."AMELIORATION";

--------------------------------------- DPE BAIE --------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpebaie as
select ID, TD007_PAROI_OPAQUE_ID, REFERENCE,DEPERDITION,TV009_COEFFICIENT_TRANSMISSION_THERMIQUE_VITRAGE_ID,
PRESENCE_SURVITRAGE, COEFFICIENT_TRANSMISSION_THERMIQUE_BAIE, TV010_COEFFICIENT_TRANSMISSION_THERMIQUE_BAIE_ID,
TV011_RESISTANCE_ADDITIONNELLE_ID, TV012_COEF_TRANSMISSION_THERMIQUE_BAIE_PROTECTION_SOLAIRE_ID, SURFACE, 
PERIMETRE, TV013_VALEUR_PONT_THERMIQUE_ID, FACTEUR_SOLAIRE, TV021_FACTEUR_SOLAIRE_ID, 
TV022_COEFFICIENT_MASQUES_PROCHES_ID, TV023_COEFFICIENT_MASQUES_LOINTAINS_HOMOGENES_ID, TV020_COEFFICIENT_ORIENTATION_ID 
FROM "REF_MARKETPLACE"."DPE"."BAIE";

---------------------------------------- DPE BATIMENT --------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpebat as
select ID, TD001_DPE_ID, BESOIN_CHAUFFAGE, DEPERDITION_ENVELOPPE, DEPERDITION_RENOUVELLEMENT_AIR, TV014_PERMEABILITE_ID, 
TV015_VALEUR_CONVENTIONNELLE_RENOUVELLEMENT_AIR_ID, TV026_CLASSE_INERTIE_ID, ALTITUDE, NOMBRE_NIVEAU, HSP_MOYENNE, 
NOMBRE_APPARTEMENTS  
FROM "REF_MARKETPLACE"."DPE"."BATIMENT";

-------------------------------- DPE CLEANGEOCODAC -------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpeclean as
select ID, NUMERO_DPE, USR_DIAGNOSTIQUEUR_ID, USR_LOGICIEL_ID, TR001_MODELE_DPE_ID,  
NOM_METHODE_DPE, VERSION_METHODE_DPE, NOM_METHODE_ETUDE_THERMIQUE, VERSION_METHODE_ETUDE_THERMIQUE, DATE_VISITE_DIAGNOSTIQUEUR, 
DATE_ETABLISSEMENT_DPE, DATE_ARRETE_TARIFS_ENERGIES, COMMENTAIRES_AMELIORATIONS_RECOMMANDATIONS, EXPLICATION_PERSONNALISEE, 
CONSOMMATION_ENERGIE, CLASSE_CONSOMMATION_ENERGIE, ESTIMATION_GES, CLASSE_ESTIMATION_GES, TR002_TYPE_BATIMENT_ID, SECTEUR_ACTIVITE,
TR012_CATEGORIE_ERP_ID, TR013_TYPE_ERP_ID, ANNEE_CONSTRUCTION, SURFACE_HABITABLE, SURFACE_THERMIQUE_LOT, TV016_DEPARTEMENT_ID, 
COMMUNE, ARRONDISSEMENT, TYPE_VOIE, NOM_RUE, NUMERO_RUE, BATIMENT, ESCALIER, ETAGE, PORTE, CODE_POSTAL,  CODE_INSEE_COMMUNE, 
CODE_INSEE_COMMUNE_ACTUALISE, NUMERO_LOT, SURFACE_COMMERCIALE_CONTRACTUELLE, PORTEE_DPE_BATIMENT, PARTIE_BATIMENT, SHON, 
SURFACE_UTILE, SURFACE_THERMIQUE_PARTIES_COMMUNES, EN_SOUTERRAIN, EN_SURFACE, NOMBRE_NIVEAUX, NOMBRE_CIRCULATIONS_VERTICALES, 
 NOMBRE_ENTREES_AVEC_SAS, NOMBRE_ENTREES_SANS_SAS,SURFACE_BAIES_ORIENTEES_NORD, SURFACE_BAIES_ORIENTEES_EST_OUEST, 
SURFACE_BAIES_ORIENTEES_SUD, SURFACE_PLANCHERS_HAUTS_DEPERDITIFS,
SURFACE_PLANCHERS_BAS_DEPERDITIFS, SURFACE_PAROIS_VERTICALES_OPAQUES_DEPERDITIVES, ORGANISME_CERTIFICATEUR, 
ADRESSE_ORGANISME_CERTIFICATEUR, DPE_VIERGE,DATE_RECEPTION_DPE, CONCAT_ADRESS, LATITUDE, LONGITUDE, RESULT_LABEL, 
RESULT_SCORE, RESULT_TYPE, RESULT_ID, RESULT_HOUSENUMBER, RESULT_NAME, RESULT_POSTCODE,RESULT_CITY, RESULT_CONTEXT,
RESULT_CITYCODE,RESULT_OLDCITYCODE,RESULT_OLDCITY 
FROM "REF_MARKETPLACE"."DPE"."CLEAN_GEOCODEC";

----------------------------------- DPE CONSOMMATION ---------------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpecon as
select ID, TD001_DPE_ID, TR006_TYPE_USAGE_ID, TR004_TYPE_ENERGIE_ID, TV042_TARIF_ENERGIE_ID, CONSOMMATION_ENERGIE_PRIMAIRE
, FRAIS_ANNUELS_ENERGIE
FROM "REF_MARKETPLACE"."DPE"."CONSOMMATION";

----------------------------------- DPE DESCRIPTIF ----------------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpedesc as
select ID, TD001_DPE_ID, TR007_TYPE_DESCRIPTIF_ID, DESCRIPTIF
FROM "REF_MARKETPLACE"."DPE"."DESCRIPTIF";

----------------------------------- DPE FACTURE -----------------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpefact as
select ID,TD001_DPE_ID,TR004_TYPE_ENERGIE_ID,TR006_TYPE_USAGE_ID,TV044_CONVERSION_KWH_ENERGIES_RELEVEES_ID,TV045_CONVERSION_KWH_CO2_ID
,TV046_EVALUATION_CONTENU_CO2_RESEAUX_ID,DESCRIPTION,ANNEE_N,ANNEE_N_1,ANNEE_N_2,UNITE_CONSOMMATION,CONSOMMATION_N,CONSOMMATION_N_1
,CONSOMMATION_N_2,COUT_N,COUT_N_1,COUT_N_2,CONSOMMATION_BATIMENT_N,CONSOMMATION_BATIMENT_N_1,CONSOMMATION_BATIMENT_N_2
,COEFFICIENT_REPARTITION_CHARGES,CONSOMMATION_LOT_N,CONSOMMATION_LOT_N_1,CONSOMMATION_LOT_N_2
FROM "REF_MARKETPLACE"."DPE"."FACTURE";

----------------------------------- DPE FICHE_TECHNIQUE -----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpefiche as
select ID, TD001_DPE_ID, TR011_SOUS_CATEGORIE_FICHE_TECHNIQUE_ID, VALEUR_RENSEIGNEE 
FROM "REF_MARKETPLACE"."DPE"."FICHE_TECHNIQUE";

----------------------------------- DPE GENERATEUR_CHAUFFAGE -----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpe_gene_chauffage as
select ID, CHAUFFAGE_COGENERATION_ID, TD011_INSTALLATION_CHAUFFAGE_ID, TR004_TYPE_ENERGIE_ID, TV045_CONVERSION_KWH_CO2_ID, 
TV046_EVALUATION_CONTENU_CO2_RESEAUX_ID, RENDEMENT_EMISSION_SYSTEME_CHAUFFAGE 
FROM "REF_MARKETPLACE"."DPE"."GENERATEUR_CHAUFFAGE";
 
----------------------------------- DPE GENERATEUR_ECS -----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpe_gene_ecs as
select ID, TD013_INSTALLATION_ECS_ID, TR004_TYPE_ENERGIE_ID, TV045_CONVERSION_KWH_CO2_ID, TV046_EVALUATION_CONTENU_CO2_RESEAUX_ID? 
COEFFICIENT_PERFORMANCE, TV032_COEFFICIENT_PERFORMANCE_ID, RPN, QP0, PUISSANCE_VEILLEUSE, TV036_PUISSANCE_VEILLEUSE_ID,
TV037_PUISSANCE_NECESSAIRE_PRODUCTION_ECS_ID, PUISSANCE_NOMINALE, TV038_PUISSANCE_NOMINALE_ID, 
TV040_RENDEMENT_DISTRIBUTION_ECS, TV047_RENDEMENT_GENERATION_ECS_ID, VOLUME_STOCKAGE, TV048_RENDEMENT_STOCKAGE_ECS_ID, 
TV049_PERTE_STOCKAGE_ECS_ID, TV041_COEFFICIENT_EMPLACEMENT_FONCTIONNEMENT_ID, TV043_PERTE_STOCKAGE_ID, 
TV019_FECS_ID, TV027_PERTES_RECUPEREES_ECS_ID 
FROM "REF_MARKETPLACE"."DPE"."GENERATEUR_ECS";
 
----------------------------------- DPE INSTALLATION_CHAUFFAGE ------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpe_ins_chauffage as
select ID, TD006_BATIMENT_ID, TR003_TYPE_INSTALLATION_CHAUFFAGE_ID, SURFACE_CHAUFFEE, NOMBRE_APPARTEMENTS_ECHANTILLON, 
SURFACE_HABITABLE_ECHANTILLON, TV025_INTERMITTENCE_ID 
FROM "REF_MARKETPLACE"."DPE"."INSTALLATION_CHAUFFAGE";

----------------------------------- DPE INSTALLATION_ECS -----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpe_ins_ecs as
select ID, TD006_BATIMENT_ID, TR005_TYPE_INSTALLATION_ECS_ID,  NOMBRE_APPARTEMENTS_ECHANTILLON,
SURFACE_HABITABLE_ECHANTILLON, BECS, TV039_FORMULE_BECS_ID, SURFACE_ALIMENTEE 
FROM "REF_MARKETPLACE"."DPE"."INSTALLATION_ECS";

----------------------------------- DPE MASQUE_SOLAIRE_LOINTAIN -----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpe_masque as
select ID, TD008_BAIE_ID, TV024_OMBRAGE_OBSTACLE_LOINTAIN_ID 
FROM "REF_MARKETPLACE"."DPE"."MASQUE_SOLAIRE_LOINTAIN";

----------------------------------- DPE NEUF -----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpe_neuf as
select ID, TD001_DPE_ID, TR004_TYPE_ENERGIE_ID, TR006_TYPE_USAGE_ID, TV044_CONVERSION_KWH_ENERGIES_RELEVEES_ID, 
TV045_CONVERSION_KWH_CO2_ID, TV046_EVALUATION_CONTENU_CO2_RESEAUX_ID, CONSOMMATION_ENERGIE_FINALE, 
CONSOMMATION_ENERGIE_PRIMAIRE, FRAIS_ANNUELS_ENERGIE 
FROM "REF_MARKETPLACE"."DPE"."NEUF";

----------------------------------- DPE PAROI OPAQUE -----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpe_paroi as
select ID, TD006_BATIMENT_ID, TR014_TYPE_PAROI_OPAQUE_ID, REFERENCE, DEPERDITION_THERMIQUE, 
TV010_COEFFICIENT_REDUCTION_DEPERDITIONS_ID , TV002_LOCAL_NON_CHAUFFE_ID, COEFFICIENT_TRANSMISSION_THERMIQUE_PAROI,
COEFFICIENT_TRANSMISSION_THERMIQUE_PAROI_NON_ISOLEE, TV003_UMUR_ID, TV004_UMUR0_ID, TV005_UPB_ID, 
TV006_UPB0_ID, TV007_UPH_ID, TV008_UPH0_ID, RESISTANCE_THERMIQUE_ISOLATION, EPAISSEUR_ISOLATION, SURFACE_PAROI 
FROM "REF_MARKETPLACE"."DPE"."PAROI_OPAQUE";

----------------------------------- DPE PONT THERMIQUE -----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpe_pont as
select ID, TD006_BATIMENT_ID, LONGUEUR, TV013_VALEUR_PONT_THERMIQUE_ID 
FROM "REF_MARKETPLACE"."DPE"."PONT_THERMIQUE";

----------------------------------- DPE PRODUCTION ENERGIE -----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_dpe_prod as
select ID, TD006_BATIMENT_ID, TR004_TYPE_ENERGIE_ID, TV045_CONVERSION_KWH_CO2_ID, PRODUCTION_ELECTRICITE_CAPTEURS_PHOTOVOLTAIQUES, 
SURFACE_CAPTEUR_PHOTOVOLTAIQUE, NOMBRE_MICRO_EOLIENNES, PRODUCTION_ELECTRICITE_MICRO_EOLIENNE, 
TD012_GENERATEUR_CHAUFFAGE_ID, PRODUCTION_COGENERATION 
FROM "REF_MARKETPLACE"."DPE"."PRODUCTION_ENERGIE";

----------------------------------- OPEN_FOOD -----------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_food as
select CODE,
URL,CREATED_DATETIME,LAST_MODIFIED_DATETIME,PRODUCT_NAME,ABBREVIATED_PRODUCT_NAME,GENERIC_NAME,QUANTITY,PACKAGING,PACKAGING_TAGS,PACKAGING_TEXT
,BRANDS,BRANDS_TAGS,CATEGORIES_EN,ORIGINS_EN,LABELS_EN,EMB_CODES,EMB_CODES_TAGS,CITIES,CITIES_TAGS,PURCHASE_PLACES,STORES,COUNTRIES_EN
,INGREDIENTS_TEXT,ALLERGENS_EN,TRACES_EN,SERVING_SIZE,SERVING_QUANTITY,NO_NUTRIMENTS,ADDITIVES_EN,INGREDIENTS_FROM_PALM_OIL_N,INGREDIENTS_THAT_MAY_BE_FROM_PALM_OIL_N
,NUTRISCORE_SCORE,NUTRISCORE_GRADE,NOVA_GROUP,PNNS_GROUPS_1,PNNS_GROUPS_2,STATES_EN,BRAND_OWNER,MAIN_CATEGORY_EN,IMAGE_URL,IMAGE_INGREDIENTS_URL
,IMAGE_NUTRITION_URL,ENERGY_KJ_100G,ENERGY_KCAL_100G,ENERGY_100G,ENERGY_FROM_FAT_100G,FAT_100G,SATURATED_FAT_100G,BUTYRIC_ACID_100G,CAPROIC_ACID_100G
,CAPRYLIC_ACID_100G,CAPRIC_ACID_100G,LAURIC_ACID_100G,MYRISTIC_ACID_100G,PALMITIC_ACID_100G,STEARIC_ACID_100G,ARACHIDIC_ACID_100G,BEHENIC_ACID_100G
,LIGNOCERIC_ACID_100G,CEROTIC_ACID_100G,MONTANIC_ACID_100G,MELISSIC_ACID_100G,MONOUNSATURATED_FAT_100G,POLYUNSATURATED_FAT_100G,OMEGA_3_FAT_100G
,ALPHA_LINOLENIC_ACID_100G,EICOSAPENTAENOIC_ACID_100G,DOCOSAHEXAENOIC_ACID_100G,OMEGA_6_FAT_100G,LINOLEIC_ACID_100G,ARACHIDONIC_ACID_100G,GAMMA_LINOLENIC_ACID_100G
,DIHOMO_GAMMA_LINOLENIC_ACID_100G,OMEGA_9_FAT_100G,OLEIC_ACID_100G,ELAIDIC_ACID_100G,GONDOIC_ACID_100G,MEAD_ACID_100G,ERUCIC_ACID_100G
,NERVONIC_ACID_100G,TRANS_FAT_100G,CHOLESTEROL_100G,CARBOHYDRATES_100G,SUGARS_100G,SUCROSE_100G,GLUCOSE_100G,FRUCTOSE_100G,LACTOSE_100G,MALTOSE_100G
,MALTODEXTRINS_100G,STARCH_100G,POLYOLS_100G,FIBER_100G,SOLUBLE_FIBER_100G,INSOLUBLE_FIBER_100G,PROTEINS_100G, CASEIN_100G,SERUM_PROTEINS_100G
,NUCLEOTIDES_100G,SALT_100G,SODIUM_100G,ALCOHOL_100G,VITAMIN_A_100G,BETA_CAROTENE_100G,VITAMIN_D_100G,VITAMIN_E_100G,VITAMIN_K_100G,VITAMIN_C_100G
,VITAMIN_B1_100G,VITAMIN_B2_100G,VITAMIN_PP_100G,VITAMIN_B6_100G,VITAMIN_B9_100G,FOLATES_100G,VITAMIN_B12_100G,BIOTIN_100G,PANTOTHENIC_ACID_100G
,SILICA_100G,BICARBONATE_100G,POTASSIUM_100G,CHLORIDE_100G,CALCIUM_100G,PHOSPHORUS_100G,IRON_100G,MAGNESIUM_100G,ZINC_100G,COPPER_100G,MANGANESE_100G
,FLUORIDE_100G,SELENIUM_100G,CHROMIUM_100G,MOLYBDENUM_100G,IODINE_100G,CAFFEINE_100G,TAURINE_100G,PH_100G,FRUITS_VEGETABLES_NUTS_100G,FRUITS_VEGETABLES_NUTS_DRIED_100G
,FRUITS_VEGETABLES_NUTS_ESTIMATE_100G,COLLAGEN_MEAT_PROTEIN_RATIO_100G,COCOA_100G,CHLOROPHYL_100G,CARBON_FOOTPRINT_100G,CARBON_FOOTPRINT_FROM_MEAT_OR_FISH_100G,NUTRITION_SCORE_FR_100G
,NUTRITION_SCORE_UK_100G,GLYCEMIC_INDEX_100G,WATER_HARDNESS_100G,CHOLINE_100G,PHYLLOQUINONE_100G,BETA_GLUCAN_100G,INOSITOL_100G,CARNITINE_100G 
FROM "REF_MARKETPLACE"."OPEN_FOOD"."FOOD";

-------------------------------------- SIREN ETABLISSEMENTS -----------------------------------------------------------
USE DATABASE REF_MARKETPLACE;

create or replace secure view sv_siren_etab as
select SIREN,NIC,SIRET,STATUTDIFFUSIONETABLISSEMENT,DATECREATIONETABLISSEMENT,TRANCHEEFFECTIFSETABLISSEMENT,
ANNEEEFFECTIFSETABLISSEMENT,ACTIVITEPRINCIPALEREGISTREMETIERSETABLISSEMENT,DATEDERNIERTRAITEMENTETABLISSEMENT,
ETABLISSEMENTSIEGE,NOMBREPERIODESETABLISSEMENT,COMPLEMENTADRESSEETABLISSEMENT,NUMEROVOIEETABLISSEMENT,
INDICEREPETITIONETABLISSEMENT,TYPEVOIEETABLISSEMENT,LIBELLEVOIEETABLISSEMENT,CODEPOSTALETABLISSEMENT,LIBELLECOMMUNEETABLISSEMENT,
LIBELLECOMMUNEETRANGERETABLISSEMENT,DISTRIBUTIONSPECIALEETABLISSEMENT,CODECOMMUNEETABLISSEMENT,CODECEDEXETABLISSEMENT,
LIBELLECEDEXETABLISSEMENT,CODEPAYSETRANGERETABLISSEMENT,LIBELLEPAYSETRANGERETABLISSEMENT,COMPLEMENTADRESSE2ETABLISSEMENT,
NUMEROVOIE2ETABLISSEMENT,INDICEREPETITION2ETABLISSEMENT,TYPEVOIE2ETABLISSEMENT,LIBELLEVOIE2ETABLISSEMENT,
CODEPOSTAL2ETABLISSEMENT,LIBELLECOMMUNE2ETABLISSEMENT,LIBELLECOMMUNEETRANGER2ETABLISSEMENT,DISTRIBUTIONSPECIALE2ETABLISSEMENT,
CODECOMMUNE2ETABLISSEMENT,CODECEDEX2ETABLISSEMENT,LIBELLECEDEX2ETABLISSEMENT,CODEPAYSETRANGER2ETABLISSEMENT,
LIBELLEPAYSETRANGER2ETABLISSEMENT,DATEDEBUT,ETATADMINISTRATIFETABLISSEMENT,ENSEIGNE1ETABLISSEMENT,ENSEIGNE2ETABLISSEMENT,
ENSEIGNE3ETABLISSEMENT,DENOMINATIONUSUELLEETABLISSEMENT,ACTIVITEPRINCIPALEETABLISSEMENT,NOMENCLATUREACTIVITEPRINCIPALEETABLISSEMENT,
CARACTEREEMPLOYEURETABLISSEMENT
FROM "REF_MARKETPLACE"."SIREN"."ETABLISSEMENT";

